name: Publish development Docker image

on:
  push:
    branches:
      - 'development'

env:
  IMAGE_NAME: driesyperman/labo3:dev

jobs:
  push_to_registry:
    name: Push image to Docker Hub with tag 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push ${{ env.IMAGE_NAME }} to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
